// Activity-log API routes
const express = require('express');
const router = express.Router();
const pool = require('../db');
const { requireLogin } = require('../middleware/auth');

router.use(requireLogin);

const ENTITY_TABLES = {
  requirement: 'crm_requirements',
  resource: 'crm_resources',
  lead: 'crm_leads'
};

// POST endpoint to create a user note against an existing CRM entity.
router.post('/', async (req, res) => {
  const { entity_type } = req.body;
  const entityId = Number.parseInt(req.body.entity_id, 10);
  const note = typeof req.body.note === 'string' ? req.body.note.trim() : '';

  if (!Object.hasOwn(ENTITY_TABLES, entity_type) || !Number.isInteger(entityId) || entityId <= 0 || !note || note.length > 5000) {
    return res.status(400).json({ error: 'Valid entity_type, entity_id, and note (max 5000 characters) are required.' });
  }

  try {
    const table = ENTITY_TABLES[entity_type];
    const [rows] = await pool.query(`SELECT id, created_by FROM ${table} WHERE id=?`, [entityId]);
    if (!rows.length) return res.status(404).json({ error: 'Entity not found.' });

    // Employees may add notes only to their own requirements.
    if (entity_type === 'requirement' && req.session.user.role === 'emp' && rows[0].created_by !== req.session.user.id) {
      return res.status(403).json({ error: 'Permission denied.' });
    }

    // Reference columns are generated by trusted domain actions, never by clients.
    const [result] = await pool.query(
      'INSERT INTO crm_activity_logs (entity_type,entity_id,note,ref_resource_id,ref_client_id,created_by) VALUES (?,?,?,?,?,?)',
      [entity_type, entityId, note, null, null, req.session.user.id]
    );
    res.status(201).json({ id: result.insertId });
  } catch (err) {
    console.error('POST activity error:', err);
    res.status(500).json({ error: 'Failed to add update.' });
  }
});

module.exports = router;

// NOTE: The table name above is selected only from the fixed ENTITY_TABLES map;
// user input is never interpolated directly into SQL.
